
DROP TABLE IF EXISTS Register;
DROP TABLE IF EXISTS Major;
DROP TABLE IF EXISTS Minor;
DROP TABLE IF EXISTS Courses;
DROP TABLE IF EXISTS Degrees;
DROP TABLE IF EXISTS Students;
DROP TABLE IF EXISTS Departments;
